import type { Story } from '../core/types';

export interface TemplateItem {
  id: string;
  name: string;
  description: string;
  story: Story;
}

export const TEMPLATE_CATALOG: TemplateItem[] = [
  {
    id: 'childrens-story',
    name: '📖 قصة أطفال',
    description: 'خط عريض ونص كبير في الأعلى ومساحة واسعة للرسوم التوضيحية أو الصور.',
    story: {
      id: 'template-children',
      title: 'قصة أطفال مصورة',
      language: 'ar',
      direction: 'rtl',
      slides: [
        {
          id: 'slide-c1',
          background: { type: 'color', value: '#fff9db' },
          elements: [
            {
              id: 'text-c1',
              type: 'text',
              x: 100,
              y: 50,
              width: 1000,
              height: 120,
              rotation: 0,
              opacity: 1,
              zIndex: 0,
              locked: false,
              hidden: false,
              animation: null,
              text: 'في غابة بعيدة وجميلة، كان هناك أرنب صغير يدعى سمسم يحب المغامرة الجريئة...',
              fontFamily: 'Cairo',
              fontSize: 32,
              color: '#d9480f',
              bold: true,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
            {
              id: 'image-c1',
              type: 'image',
              x: 200,
              y: 200,
              width: 800,
              height: 400,
              rotation: 0,
              opacity: 1,
              zIndex: 1,
              locked: false,
              hidden: false,
              animation: null,
              src: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=800&auto=format&fit=crop',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'science-lesson',
    name: '🧪 درس علوم مبسط',
    description: 'رسم توضيحي علمي مع عنوان توضيحي وشرح تفصيلي بالأسفل.',
    story: {
      id: 'template-science',
      title: 'درس العلوم: المجموعة الشمسية',
      language: 'ar',
      direction: 'rtl',
      slides: [
        {
          id: 'slide-s1',
          background: { type: 'gradient', value: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)' },
          elements: [
            {
              id: 'text-s1',
              type: 'text',
              x: 80,
              y: 40,
              width: 1040,
              height: 70,
              rotation: 0,
              opacity: 1,
              zIndex: 0,
              locked: false,
              hidden: false,
              animation: null,
              text: 'الموضوع: دوران الكواكب حول الشمس',
              fontFamily: 'Cairo',
              fontSize: 28,
              color: '#00f2fe',
              bold: true,
              italic: false,
              underline: false,
              align: 'right',
              dir: 'rtl',
            },
            {
              id: 'image-s1',
              type: 'image',
              x: 100,
              y: 130,
              width: 600,
              height: 480,
              rotation: 0,
              opacity: 1,
              zIndex: 1,
              locked: false,
              hidden: false,
              animation: null,
              src: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=800&auto=format&fit=crop',
            },
            {
              id: 'text-s2',
              type: 'text',
              x: 740,
              y: 130,
              width: 380,
              height: 480,
              rotation: 0,
              opacity: 1,
              zIndex: 2,
              locked: false,
              hidden: false,
              animation: null,
              text: 'الشرح العلمي المبسط:\n\nتدور كواكب المجموعة الشمسية الثمانية حول الشمس في مدارات بيضاوية.\n\nتأخذ الأرض حوالي 365 يوماً لإكمال دورة كاملة حول الشمس، وهي الدورة التي تسبب تعاقب الفصول الأربعة.',
              fontFamily: 'Cairo',
              fontSize: 20,
              color: '#e1e2e6',
              bold: false,
              italic: false,
              underline: false,
              align: 'right',
              dir: 'rtl',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'quiz',
    name: '❓ سؤال واختيار',
    description: 'قالب تفاعلي يحتوي على سؤال في الأعلى وخيارات متعددة مرتبة بالأسفل.',
    story: {
      id: 'template-quiz',
      title: 'مسابقة علمية تفاعلية',
      language: 'ar',
      direction: 'rtl',
      slides: [
        {
          id: 'slide-q1',
          background: { type: 'color', value: '#eef2f3' },
          elements: [
            {
              id: 'text-q-title',
              type: 'text',
              x: 100,
              y: 80,
              width: 1000,
              height: 100,
              rotation: 0,
              opacity: 1,
              zIndex: 0,
              locked: false,
              hidden: false,
              animation: null,
              text: 'سؤال: ما هو الكوكب الأقرب إلى الشمس في المجموعة الشمسية؟',
              fontFamily: 'Cairo',
              fontSize: 30,
              color: '#2c3e50',
              bold: true,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
            {
              id: 'text-q-opt1',
              type: 'text',
              x: 200,
              y: 250,
              width: 800,
              height: 60,
              rotation: 0,
              opacity: 1,
              zIndex: 1,
              locked: false,
              hidden: false,
              animation: null,
              text: 'أ) كوكب المريخ (Mars)',
              fontFamily: 'Cairo',
              fontSize: 22,
              color: '#2980b9',
              bold: false,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
            {
              id: 'text-q-opt2',
              type: 'text',
              x: 200,
              y: 350,
              width: 800,
              height: 60,
              rotation: 0,
              opacity: 1,
              zIndex: 2,
              locked: false,
              hidden: false,
              animation: null,
              text: 'ب) كوكب الزهرة (Venus)',
              fontFamily: 'Cairo',
              fontSize: 22,
              color: '#2980b9',
              bold: false,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
            {
              id: 'text-q-opt3',
              type: 'text',
              x: 200,
              y: 450,
              width: 800,
              height: 60,
              rotation: 0,
              opacity: 1,
              zIndex: 3,
              locked: false,
              hidden: false,
              animation: null,
              text: 'ج) كوكب عطارد (Mercury) [الإجابة الصحيحة]',
              fontFamily: 'Cairo',
              fontSize: 22,
              color: '#27ae60',
              bold: true,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'educational-deck',
    name: '📚 عرض تعليمي كلاسيكي',
    description: 'تصميم عروض كلاسيكي: عنوان في الأعلى وعناصر نقطية (bullet list) بالأسفل.',
    story: {
      id: 'template-edu',
      title: 'أهمية البرمجة للذكاء الاصطناعي',
      language: 'ar',
      direction: 'rtl',
      slides: [
        {
          id: 'slide-e1',
          background: { type: 'color', value: '#1e1e24' },
          elements: [
            {
              id: 'text-e-title',
              type: 'text',
              x: 80,
              y: 60,
              width: 1040,
              height: 80,
              rotation: 0,
              opacity: 1,
              zIndex: 0,
              locked: false,
              hidden: false,
              animation: null,
              text: 'لماذا نتعلم البرمجة؟',
              fontFamily: 'Cairo',
              fontSize: 36,
              color: '#ffffff',
              bold: true,
              italic: false,
              underline: false,
              align: 'right',
              dir: 'rtl',
            },
            {
              id: 'text-e-bullets',
              type: 'text',
              x: 80,
              y: 180,
              width: 1040,
              height: 400,
              rotation: 0,
              opacity: 1,
              zIndex: 1,
              locked: false,
              hidden: false,
              animation: null,
              text: '• تنمية مهارات التفكير المنطقي والتحليلي لحل المشكلات.\n\n• فهم كيفية عمل التطبيقات والأنظمة والذكاء الاصطناعي.\n\n• فتح فرص عمل واعدة في مجالات الحوسبة السحابية وهندسة البيانات.\n\n• إمكانية ابتكار وتطوير حلول وأدوات لتسهيل العمل والحياة اليومية.',
              fontFamily: 'Cairo',
              fontSize: 22,
              color: '#ced4da',
              bold: false,
              italic: false,
              underline: false,
              align: 'right',
              dir: 'rtl',
            },
          ],
        },
      ],
    },
  },
  {
    id: 'activity-page',
    name: '🎨 صفحة نشاط تفاعلي',
    description: 'تصميم ذو شاشة مقسمة لتمثيل نشاط تفاعلي أو صورة مع تعليقات مخصصة.',
    story: {
      id: 'template-activity',
      title: 'نشاط تفاعلي للطلاب',
      language: 'ar',
      direction: 'rtl',
      slides: [
        {
          id: 'slide-a1',
          background: { type: 'gradient', value: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)' },
          elements: [
            {
              id: 'text-a-instruction',
              type: 'text',
              x: 100,
              y: 60,
              width: 1000,
              height: 60,
              rotation: 0,
              opacity: 1,
              zIndex: 0,
              locked: false,
              hidden: false,
              animation: null,
              text: '🎨 نشاط اليوم: صف ما تراه في الصورة مستعيناً بخيالك',
              fontFamily: 'Cairo',
              fontSize: 24,
              color: '#2c3e50',
              bold: true,
              italic: false,
              underline: false,
              align: 'center',
              dir: 'rtl',
            },
            {
              id: 'image-a-main',
              type: 'image',
              x: 100,
              y: 140,
              width: 500,
              height: 450,
              rotation: 0,
              opacity: 1,
              zIndex: 1,
              locked: false,
              hidden: false,
              animation: null,
              src: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop',
            },
            {
              id: 'text-a-notes',
              type: 'text',
              x: 640,
              y: 140,
              width: 460,
              height: 450,
              rotation: 0,
              opacity: 1,
              zIndex: 2,
              locked: false,
              hidden: false,
              animation: null,
              text: 'توجيهات للطالب:\n\n1. ركّز على الألوان والتفاصيل الكونية.\n2. فكر كيف تلتقط التلسكوبات الضوء من النجوم.\n3. أكتب فقرة قصيرة لا تتجاوز 4 أسطر تصف فيها شعورك وأنت تنظر إلى الفضاء الفسيح.',
              fontFamily: 'Cairo',
              fontSize: 20,
              color: '#34495e',
              bold: false,
              italic: false,
              underline: false,
              align: 'right',
              dir: 'rtl',
            },
          ],
        },
      ],
    },
  },
];
